//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changesv  to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backlog_managment.Student
{


    public partial class Stdash
    {
    }
}
